name: gerenciamento_rpg
description: Sistema de gerenciamento de campanhas de RPG
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  provider: ^6.1.5+1
  flutter_slidable: ^3.0.0
  google_fonts: ^6.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
